BOT_NAME = 'startup_search_crawler'
SPIDER_MODULES = ['startup_search.crawler.spiders']
NEWSPIDER_MODULE = 'startup_search.crawler.spiders'

ROBOTSTXT_OBEY = True
CONCURRENT_REQUESTS = 16
CONCURRENT_REQUESTS_PER_DOMAIN = 1
DOWNLOAD_DELAY = 0.5
RANDOMIZE_DOWNLOAD_DELAY = True
DOWNLOAD_TIMEOUT = 12
RETRY_TIMES = 2
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 0.5
AUTOTHROTTLE_MAX_DELAY = 8
USER_AGENT = 'StartupSearchBot/0.2 (+local research dashboard)'
LOG_LEVEL = 'INFO'
TELNETCONSOLE_ENABLED = False
